---
title: "data exploration"
author: "Amy"
date: "29/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readstata13)
library(arsenal)
library(Hmisc)
library(MASS)
library(kableExtra)
library(apaTables)
```

```{r}
codebook <- read_csv(here("inputs/data/codebook.csv"))
```



```{r, warning=FALSE}
isrdata <- read.dta13(here("inputs/data/Instructor-Student Relationships Experiment Data_Anonymous.dta"))
```

```{r}
expdata <- isrdata %>%
  filter(use == 1)
```

```{r}
summary(tableby(treatment ~  s1_sim + s1_tsr + s2_sim + s2_tsr + t2_sim1 + t2_tsr + grade + std_grade + t2_finalexam + f17_enrolled + ir_f16_gpa + s_female,
                data = isrdata)) %>%
  kable()
```

```{r}
rcorr(as.matrix(isrdata %>% 
                  dplyr::select(s1_sim, s1_tsr, s2_sim, s2_tsr, t2_sim1, t2_tsr, grade, std_grade, t2_finalexam, ir_f16_gpa)))
```

```{r}
apa.cor.table(isrdata %>% 
                  dplyr::select(s1_sim, s1_tsr, s2_sim, s2_tsr, t2_sim1, t2_tsr, grade, std_grade, t2_finalexam, ir_f16_gpa))
```


```{r}
colSums(is.na(expdata))
```


```{r}
instructorrace <- expdata %>%
  dplyr::select(teacherid,
         t1_race_1, t1_race_2, t1_race_3, t1_race_4, t1_race_5, t1_race_6, t1_race_7, t_multi_race) %>%
  unique() %>%
  dplyr::summarize(white = sum(t1_race_1, na.rm = TRUE)/n(),
            black = sum(t1_race_2, na.rm = TRUE)/n(),
            hispanic = sum(t1_race_3, na.rm = TRUE)/n(),
            asian = sum(t1_race_4, na.rm = TRUE)/n(),
            americanindian = sum(t1_race_5, na.rm = TRUE)/n(),
            middleeastern = sum(t1_race_6, na.rm = TRUE)/n(),
            other = sum(t1_race_7, na.rm = TRUE)/n(),
            mixed = sum(t_multi_race > 1, na.rm = TRUE)/n(),
            total = n())
```
```{r}
studentrace <- expdata %>%
  dplyr::select(id,
         s1_race_1, s1_race_2, s1_race_3, s1_race_4, s1_race_5, s1_race_6, s1_race_7, s_multi_race) %>%
  unique() %>%
  dplyr::summarize(white = sum(s1_race_1, na.rm = TRUE)/n(),
            black = sum(s1_race_2, na.rm = TRUE)/n(),
            hispanic = sum(s1_race_3, na.rm = TRUE)/n(),
            asian = sum(s1_race_4, na.rm = TRUE)/n(),
            americanindian = sum(s1_race_5, na.rm = TRUE)/n(),
            middleeastern = sum(s1_race_6, na.rm = TRUE)/n(),
            other = sum(s1_race_7, na.rm = TRUE)/n(),
            mixed = sum(s_multi_race > 1, na.rm = TRUE)/n(),
            total = n())
```



```{r}
expdata %>%
  group_by(treatment) %>%
  summarize(white = sum(s1_race_1, na.rm = TRUE)/n(),
            black = sum(s1_race_2, na.rm = TRUE)/n(),
            hispanic = sum(s1_race_3, na.rm = TRUE)/n(),
            asian = sum(s1_race_4, na.rm = TRUE)/n(),
            americanindian = sum(s1_race_5, na.rm = TRUE)/n(),
            middleeastern = sum(s1_race_6, na.rm = TRUE)/n(),
            other = sum(s1_race_7, na.rm = TRUE)/n(),
            total = n())
```
```{r}
expdata %>%
  group_by(treatment) %>%
  summarize(meanage = mean(s1_age, na.rm = TRUE))
```
```{r}
expdata %>%
  group_by(treatment) %>%
  summarise(prestudentsimilarity = mean(s1_sim, na.rm = TRUE),
            prestudentISR = mean(s1_tsr),
            poststudentsimilarity = mean(s2_sim, na.rm = TRUE),
            poststudentISR = mean(s2_tsr, na.rm = TRUE),
            postinstructorsimilarity = mean(t2_sim1, na.rm = TRUE),
            postinstructorISR = mean(t2_tsr, na.rm = TRUE),
            standardgrade = mean(grade_sd, na.rm = TRUE))
```

```{r}
summary(lm(data = isrdata, s1_sim ~ treatment))
```
```{r}
summary(lm(data = isrdata, s2_sim ~ treatment))
```
```{r}
summary(lm(data = isrdata, s2_tsr ~ treatment + s1_tsr))
```
```{r}
summary(polr(formula = as.factor(t2_sim1) ~ treatment, data = isrdata, Hess = TRUE))
```

```{r}
summary(lm(data = isrdata, s2_tsr ~ treatment))
```

```{r}
summary(lm(data = isrdata, grade ~ treatment + s1_female + ir_f16_gpa))
```

```{r}
summary(lm(data = isrdata %>% filter(obj_exam == 1), t2_finalexam ~ treatment + s1_female + ir_f16_gpa))
```

```{r}
summary(glm(data = isrdata, f17_enrolled ~ treatment + s1_female + ir_f16_gpa, family = "binomial"))
```

```{r studentfirstsimilarity, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(!is.na(s1_sim)) %>%
  finalfit("s1_sim", "treatment") %>%
  knitr::kable(caption = "Effect of treatment on immediate student similarity rating",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r studentsecondsimilarity, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(!is.na(s2_sim)) %>%
  finalfit("s2_sim", "treatment") %>%
  knitr::kable(caption = "Effect of treatment on end of semester student similarity rating",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r studentsecondrelationship, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(!is.na(s2_tsr) & !is.na(s1_tsr)) %>%
  finalfit("s2_tsr", c("treatment", "s1_tsr")) %>%
  knitr::kable(caption = "Effect of treatment on end of semester student ISR rating, controlling for anticipated ISR",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r teachersecondrelationship, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(!is.na(t2_tsr)) %>%
  finalfit("t2_tsr", c("treatment")) %>%
  knitr::kable(caption = "Effect of treatment on end of semester instructor ISR rating",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r grade, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(!is.na(s1_female) & !is.na(ir_f16_gpa) & !is.na(grade) & s1_female > -99) %>%
  dplyr::select(s1_female, ir_f16_gpa, grade, s1_female, treatment) %>%
  finalfit("grade", c("treatment",  "s1_female", "ir_f16_gpa")) %>%
  knitr::kable(caption = "Effect of treatment on course grade, controlling for student gender and prior GPA",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r examgrade, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(obj_exam == 1) %>%
  filter(!is.na(s1_female) & !is.na(ir_f16_gpa) & !is.na(t2_finalexam) & s1_female > -99) %>%
  finalfit("t2_finalexam", c("treatment",  "s1_female", "ir_f16_gpa")) %>%
  knitr::kable(caption = "Effect of treatment on objectively graded exam grade, controlling for student gender and prior GPA",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```


```{r teachersecondsimilarity, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  filter(!is.na(t2_sim1)) %>%
  mutate(t2_sim1 = as.factor(t2_sim1)) %>%
  finalfit("t2_sim1", "treatment") %>%
  knitr::kable(caption = "Effect of treatment on end of semester instructor similarity rating",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r enrollmentfall, echo=FALSE, warning=FALSE, message=FALSE}
expdata %>%
  mutate(f17_enrolled = as.factor(f17_enrolled)) %>%
  filter(!is.na(s1_female) & !is.na(ir_f16_gpa) & !is.na(f17_enrolled) & s1_female > -99) %>%
  finalfit("f17_enrolled", c("treatment",  "s1_female", "ir_f16_gpa")) %>%
  knitr::kable(caption = "Effect of treatment on enrollment in next Fall 2017, controlling for student gender and prior GPA",
               booktabs = TRUE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
```

```{r}
expdata %>% filter(!is.na(s1_sim)) %>%
  ggplot(aes(x = s1_sim, fill = treatment)) +
  geom_histogram(position = "dodge")

theirs <- isrdata %>%
  filter(use == 1) %>%
  dplyr::select(teacherid) %>%
  unique()

mine <- expdata %>%
  dplyr::select(teacherid) %>%
  unique()
```

```{r}
expdata %>% filter(!is.na(s2_sim)) %>%
  ggplot(aes(x = s2_sim, fill = treatment)) +
  geom_histogram(position = "dodge")
```

```{r}
expdata %>% filter(!is.na(s2_tsr) & !is.na(s1_tsr)) %>%
  ggplot(aes(x = s2_tsr, fill = treatment)) +
  geom_histogram(position = "dodge")
```

```{r}
expdata %>% filter(!is.na(t2_tsr)) %>%
  ggplot(aes(x = t2_tsr, fill = treatment)) +
  geom_histogram(position = "dodge")
```

```{r}
expdata %>% filter(!is.na(s1_female) & !is.na(ir_f16_gpa) & !is.na(grade) & s1_female > -99) %>%
  ggplot(aes(x = grade, fill = treatment)) +
  geom_histogram(position = "dodge")
```

```{r}
expdata %>% filter(obj_exam == 1) %>% filter(!is.na(s1_female) & !is.na(ir_f16_gpa) & !is.na(t2_finalexam) & s1_female > -99) %>%
  ggplot(aes(x = t2_finalexam, fill = treatment)) +
  geom_histogram(position = "dodge")
```

```{r}
expdata %>% filter(!is.na(t2_sim1)) %>%
  ggplot(aes(x = t2_sim1, fill = treatment)) +
  geom_bar(position = "dodge")
```

```{r}
expdata %>% 
  mutate(f17_enrolled = as.factor(f17_enrolled)) %>% 
  filter(!is.na(s1_female) & !is.na(ir_f16_gpa) & !is.na(f17_enrolled) & s1_female > -99) %>%
  ggplot(aes(x = f17_enrolled, fill = treatment)) +
  geom_bar(position = "dodge")
```

```{r s1simcorrelation, echo=FALSE, warning=FALSE, message=FALSE}
# Make the summary stats part of the table
summary <- expdata %>% 
  dplyr::select(treatment, 
                s1_sim1, s1_sim2, s1_sim3, s1_sim4, s1_sim5, s1_sim6) %>%
  summary_factorlist("treatment", 
                     c("s1_sim1", "s1_sim2", "s1_sim3", "s1_sim4", "s1_sim5", "s1_sim6"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = FALSE,
                     add_row_totals = TRUE,
                     include_row_missing_col = TRUE,
                     col_totals_rowname = "",
                     total_col = TRUE,
                     col_totals_prefix = "N (%) = ") %>%
  dplyr::select("Total N", "Missing N", "Total")

# Make the correlation matrix part of the table
matrix <- data.frame(apaCorr(as.matrix(expdata %>% 
                  dplyr::select(s1_sim1, s1_sim2, s1_sim3, s1_sim4, s1_sim5, s1_sim6)))) 

# Combine the summary and correlation tables
table <- summary %>%
  bind_cols(matrix) %>%
  rename("Mean (SD)" = Total, N = "Total N", Missing = "Missing N")

# Put in a table.
table %>%
  kable(caption = "Correlation matrix for initial student similarity scale",
        booktabs = TRUE) %>%
  kable_styling(latex_options = c("scale_down"))
```

```{r s1tsrcorrelation, echo=FALSE, warning=FALSE, message=FALSE}
# Make the summary stats part of the table
summary <- expdata %>% 
  dplyr::select(treatment, 
                s1_tsr1, s1_tsr2, s1_tsr3, s1_tsr4, s1_tsr5, s1_tsr6, s1_tsr7) %>%
  summary_factorlist("treatment", 
                     c("s1_tsr1", "s1_tsr2", "s1_tsr3", "s1_tsr4", "s1_tsr5", "s1_tsr6", "s1_tsr7"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = FALSE,
                     add_row_totals = TRUE,
                     include_row_missing_col = TRUE,
                     col_totals_rowname = "",
                     total_col = TRUE,
                     col_totals_prefix = "N (%) = ") %>%
  dplyr::select("Total N", "Missing N", "Total")

# Make the correlation matrix part of the table
matrix <- data.frame(apaCorr(as.matrix(expdata %>% 
                  dplyr::select(s1_tsr1, s1_tsr2, s1_tsr3, s1_tsr4, s1_tsr5, s1_tsr6, s1_tsr7)))) 

# Combine the summary and correlation tables
table <- summary %>%
  bind_cols(matrix) %>%
  rename("Mean (SD)" = Total, N = "Total N", Missing = "Missing N")

# Put in a table.
table %>%
  kable(caption = "Correlation matrix for initial student similarity scale",
        booktabs = TRUE) %>%
  kable_styling(latex_options = c("scale_down"))
```

```{r s2simcorrelation, echo=FALSE, warning=FALSE, message=FALSE}
# Make the summary stats part of the table
summary <- expdata %>% 
  dplyr::select(treatment, 
                s2_sim1, s2_sim2, s2_sim3, s2_sim4, s2_sim5, s2_sim6) %>%
  summary_factorlist("treatment", 
                     c("s2_sim1", "s2_sim2", "s2_sim3", "s2_sim4", "s2_sim5", "s2_sim6"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = FALSE,
                     add_row_totals = TRUE,
                     include_row_missing_col = TRUE,
                     col_totals_rowname = "",
                     total_col = TRUE,
                     col_totals_prefix = "N (%) = ") %>%
  dplyr::select("Total N", "Missing N", "Total")

# Make the correlation matrix part of the table
matrix <- data.frame(apaCorr(as.matrix(expdata %>% 
                  dplyr::select(s2_sim1, s2_sim2, s2_sim3, s2_sim4, s2_sim5, s2_sim6)))) 

# Combine the summary and correlation tables
table <- summary %>%
  bind_cols(matrix) %>%
  rename("Mean (SD)" = Total, N = "Total N", Missing = "Missing N")

# Put in a table.
table %>%
  kable(caption = "Correlation matrix for initial student similarity scale",
        booktabs = TRUE) %>%
  kable_styling(latex_options = c("scale_down"))
```

```{r s2tsrcorrelation, echo=FALSE, warning=FALSE, message=FALSE}
# Make the summary stats part of the table
summary <- expdata %>% 
  dplyr::select(treatment, 
                s2_tsr1, s2_tsr2, s2_tsr3, s2_tsr4, s2_tsr5, s2_tsr6, s2_tsr7) %>%
  summary_factorlist("treatment", 
                     c("s2_tsr1", "s2_tsr2", "s2_tsr3", "s2_tsr4", "s2_tsr5", "s2_tsr6", "s2_tsr7"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = FALSE,
                     add_row_totals = TRUE,
                     include_row_missing_col = TRUE,
                     col_totals_rowname = "",
                     total_col = TRUE,
                     col_totals_prefix = "N (%) = ") %>%
  dplyr::select("Total N", "Missing N", "Total")

# Make the correlation matrix part of the table
matrix <- data.frame(apaCorr(as.matrix(expdata %>% 
                  dplyr::select(s2_tsr1, s2_tsr2, s2_tsr3, s2_tsr4, s2_tsr5, s2_tsr6, s2_tsr7)))) 

# Combine the summary and correlation tables
table <- summary %>%
  bind_cols(matrix) %>%
  rename("Mean (SD)" = Total, N = "Total N", Missing = "Missing N")

# Put in a table.
table %>%
  kable(caption = "Correlation matrix for initial student similarity scale",
        booktabs = TRUE) %>%
  kable_styling(latex_options = c("scale_down"))
```

```{r t2tsrcorrelation, echo=FALSE, warning=FALSE, message=FALSE}
# Make the summary stats part of the table
summary <- expdata %>% 
  dplyr::select(treatment, 
                t2_tsr1, t2_tsr2, t2_tsr3, t2_tsr4, t2_tsr5, t2_tsr6, t2_tsr7) %>%
  summary_factorlist("treatment", 
                     c("t2_tsr1", "t2_tsr2", "t2_tsr3", "t2_tsr4", "t2_tsr5", "t2_tsr6", "t2_tsr7"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = FALSE,
                     add_row_totals = TRUE,
                     include_row_missing_col = TRUE,
                     col_totals_rowname = "",
                     total_col = TRUE,
                     col_totals_prefix = "N (%) = ") %>%
  dplyr::select("Total N", "Missing N", "Total")

# Make the correlation matrix part of the table
matrix <- data.frame(apaCorr(as.matrix(expdata %>% 
                  dplyr::select(t2_tsr1, t2_tsr2, t2_tsr3, t2_tsr4, t2_tsr5, t2_tsr6, t2_tsr7)))) 

# Combine the summary and correlation tables
table <- summary %>%
  bind_cols(matrix) %>%
  rename("Mean (SD)" = Total, N = "Total N", Missing = "Missing N")

# Put in a table.
table %>%
  kable(caption = "Correlation matrix for initial student similarity scale",
        booktabs = TRUE) %>%
  kable_styling(latex_options = c("scale_down"))
```

```{r}
expdata %>%
  dplyr::select(treatment, 
                s1_sim, s1_tsr, s2_sim, s2_tsr, t2_sim1, t2_tsr, 
                grade, std_grade, t2_finalexam, ir_f16_gpa, f17_enrolled, 
                s1_female, n_course) %>%
  missing_pattern()
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
substudentsecondsimilaritymodel <- lm(data = expdata %>% filter(s_firstgen == 1),
                                     formula = s2_sim ~ treatment + n_course + race_match + gend_match + age_dif,
                                     na.action = na.omit)
substudentsecondrelationshipmodel <- lm(data = expdata %>% filter(s_firstgen == 1),
                                     formula = s2_tsr ~ treatment + n_course + race_match + gend_match + age_dif,
                                     na.action = na.omit)
substdgrademodel <- lm(data = expdata %>% filter(s_firstgen == 1),
                      formula = grade ~ treatment + ir_f16_gpa + n_course + race_match + gend_match + age_dif,
                                     na.action = na.omit)
```

```{r submodeltable, results='asis', echo=FALSE, warning=FALSE, message=FALSE}
# Make table to display model results
stargazer(substudentsecondsimilaritymodel,
          substudentsecondrelationshipmodel,
          substdgrademodel,
          title = "Additional model results",
          align = TRUE,
          no.space = TRUE,
          omit.stat=c("ser","f"),
          column.sep.width = "-10pt",
          label = "tab:modeltable",
          type = "latex",
          header = FALSE,
          dep.var.labels = c("Student Similarity 2",
                             "Student ISR 2",
                             "Standardized course grade"),
          covariate.labels = c("Treatment",
                               "CGPA", 
                               "Course size",
                               "Matching racial self-ID", "Matching gender self-ID", "Age difference")
          )
```

```{r causaldiagram2, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Diagram of desired causal sequence"}
mermaid("
graph LR
A{intervention}-->|1|B[student similarity perception]
A-->|2|C[instructor similarity perception]
B-->|3|D[ISR]
C-->|4|D[ISR]
D-->|5|E(grades)
D-->|6|F(persistence)
E-->|7|F
")
```


```{r}
studentfirstsimilaritymodel <- lm(data = expdata,
                                  formula = s1_sim ~ treatment + n_course + teacherid,
                                     na.action = na.omit)
studentsecondsimilaritymodel <- lm(data = expdata,
                                   formula = s2_sim ~ treatment + n_course + teacherid,
                                     na.action = na.omit)
studentsecondrelationshipmodel <- lm(data = expdata,
                                     formula = s2_tsr ~ treatment + s1_tsr + n_course + teacherid,
                                     na.action = na.omit)
teachersecondrelationshipmodel <- lm(data = expdata,
                                     formula = t2_tsr ~ treatment + n_course + teacherid,
                                     na.action = na.omit)
grademodel <- lm(data = expdata,
                 formula = grade ~ treatment + s1_female + ir_f16_gpa + n_course + teacherid,
                                     na.action = na.omit)
examgrademodel <- lm(data = expdata %>% filter(obj_exam == 1),
                     formula = t2_finalexam ~ treatment + s1_female + ir_f16_gpa + n_course + teacherid,
                                     na.action = na.omit)
teachersecondsimilarity <- polr(formula = as.factor(t2_sim1) ~ treatment + teacherid,
                                data = expdata,
                                Hess = TRUE,
                                     na.action = na.omit)


stargazer(studentfirstsimilaritymodel,
          studentsecondsimilaritymodel,
          studentsecondrelationshipmodel,
          teachersecondrelationshipmodel,
          grademodel,
          examgrademodel,
          teachersecondsimilarity,
          omit = c("teacherid"),
          omit.labels = c("Instructor fixed effect"))
```


```{r}
ddata <- expdata %>%
  dplyr::select(treatment,
                s1_sim, s1_tsr, 
                s2_sim, s2_tsr, 
                t2_sim1, t2_tsr,
                grade, std_grade, 
                t2_finalexam, f17_enrolled,
                obj_exam,
                s_firstgen,
                s_hisp_black,
                year,
                s_firstgen) %>%
  mutate(all = 1)

write_csv(ddata, here("takingittothenextlevel/ddata.csv"))
```

```{r}
teststudentfirstsimilaritymodel <- lm(data = expdata,
                                  formula = s1_sim ~ treatment + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                     na.action = na.omit)
teststudentsecondsimilaritymodel <- lm(data = expdata,
                                   formula = s2_sim ~ treatment + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                     na.action = na.omit)
teststudentsecondrelationshipmodel <- lm(data = expdata,
                                     formula = s2_tsr ~ treatment + s1_tsr + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                     na.action = na.omit)
testteachersecondrelationshipmodel <- lm(data = expdata,
                                     formula = t2_tsr ~ treatment + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                     na.action = na.omit)
testgrademodel <- lm(data = expdata,
                 formula = grade ~ treatment + s1_female + ir_f16_gpa + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                     na.action = na.omit)
testexamgrademodel <- lm(data = expdata %>% filter(obj_exam == 1),
                     formula = t2_finalexam ~ treatment + s1_female + ir_f16_gpa + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                     na.action = na.omit)
testteachersecondsimilarity <- polr(formula = as.factor(t2_sim1) ~ treatment + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                                data = expdata,
                                Hess = TRUE,
                                     na.action = na.omit)
testenrollmentfallmodel <- glm(data = expdata,
                           formula = f17_enrolled ~ treatment + s1_female + ir_f16_gpa + teacherid + s_female + s_race + s_firstgen + ir_f16_gpa + year,
                           family = "binomial",
                                     na.action = na.omit)
```

```{r testmodeltable, results='asis', echo=FALSE, warning=FALSE, message=FALSE}
# Make table to display model results
stargazer(teststudentfirstsimilaritymodel,
          teststudentsecondsimilaritymodel,
          teststudentsecondrelationshipmodel,
          testteachersecondrelationshipmodel,
          testgrademodel,
          testexamgrademodel,
          testteachersecondsimilarity,
          testenrollmentfallmodel,
          title = "Replication model results",
          align = TRUE,
          ci = TRUE,
          float.env = "sidewaystable",
          no.space = TRUE,
          omit.stat=c("ser","f"),
          column.sep.width = "-10pt",
          label = "tab:modeltable",
          type = "latex",
          header = FALSE,
          initial.zero = FALSE,
          omit = c("teacherid"),
          omit.labels = c("Instructor fixed effect"))
```

```{r}
ols_plot_resid_qq(studentfirstsimilaritymodel)
```


```{r}
ols_plot_resid_fit(studentfirstsimilaritymodel)
```

```{r}
ols_plot_resid_hist(studentfirstsimilaritymodel)
```
